// 5) Ligo o primeiro interruptor e deixo ligado alguns segundos, depois desligo e ligo o segundo interruptor,
// deixo ligado e vou ate uma das salas. Se a lâmpada tiver desligada mas um pouco quente, ela pertence ao primeiro interruptor,
// se tiver ligada pertence ao segundo interruptor, se tiver desligada e fria, pertence ao terceiro interruptor.
// Descobrindo uma sala eu faço o mesmo processo e consigo descobrir as outras duas. 